
-- 模拟用户数据
INSERT INTO my_db_stu.user (id, userAccount, userPassword, userName, userAvatar,userNumber, userProfile, userRole) VALUES (1, 'admin', 'b0dd3697a192885d7c055db46155b26a', 'admin', 'https://marone-1326817243.cos.ap-beijing.myqcloud.com/user_avatar/1/admin.png', '18856565656','软件工程', 'admin');
INSERT INTO my_db_stu.user (id, userAccount, userPassword, userName, userAvatar,userNumber,  userProfile, userRole) VALUES (2, 'mar1', 'b0dd3697a192885d7c055db46155b26a', '小学生mar1', 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png','18865656565','软件工程', 'user');

-- 模拟代码生成器数据
INSERT INTO my_db_stu.generator (id, name, description, basePackage, version, author, tags, picture, fileConfig, modelConfig, distPath, status, userId) VALUES (1, '数学与计算机学院', '软件工程', 'mar1', '1班', 'mar1', '["Java"]', 'https://pic.yupi.icu/1/_r0_c1851-bf115939332e.jpg', '{}', '{}', null, 0, 1);
INSERT INTO my_db_stu.generator (id, name, description, basePackage, version, author, tags, picture, fileConfig, modelConfig, distPath, status, userId) VALUES (2, '数学与计算机学院', '网络空间与安全', 'mar1', '1班', 'mar1', '["Java"]', 'https://pic.yupi.icu/1/_r0_c0726-7e30f8db802a.jpg', '{}', '{}', null, 0, 1);
INSERT INTO my_db_stu.generator (id, name, description, basePackage, version, author, tags, picture, fileConfig, modelConfig, distPath, status, userId) VALUES (3, '数学与计算机学院', '计算机科学与技术', 'mar1', '1班', 'mar1', '["Java", "前端"]', 'https://pic.yupi.icu/1/_r1_c0cf7-f8e4bd865b4b.jpg', '{}', '{}', null, 0, 1);
INSERT INTO my_db_stu.generator (id, name, description, basePackage, version, author, tags, picture, fileConfig, modelConfig, distPath, status, userId) VALUES (4, '数学与计算机学院', '大数据科学与技术', 'mar1', '1班', 'mar1', '["Java", "前端"]', 'https://pic.yupi.icu/1/_r1_c1c15-79cdecf24aed.jpg', '{}', '{}', null, 0, 1);
INSERT INTO my_db_stu.generator (id, name, description, basePackage, version, author, tags, picture, fileConfig, modelConfig, distPath, status, userId) VALUES (5, '数学与计算机学院', '软件工程', 'mar1', '1班', 'mar1', '["Java", "前端"]', 'https://pic.yupi.icu/1/_r1_c0709-8e80689ac1da.jpg', '{}', '{}', null, 0, 1);